[versions]
schema-validator = '1.0.87'
earcut4j = '2.2.2'
flatbuffers = '22.10.26'
flatgeobuf = '3.24.0'

[libraries]
# foundation
schema-validator = { module = "com.networknt:json-schema-validator", version.ref = "schema-validator" }

# gltf
earcut4j = { module = "io.github.earcut4j:earcut4j", version.ref = "earcut4j" }

# flatgeobuf
flatbuffers = { module = "com.google.flatbuffers:flatbuffers-java", version.ref = "flatbuffers" }
flatgeobuf = { module = "org.wololo:flatgeobuf", version.ref = "flatgeobuf" }

[bundles]
